### ISSUE TITLE
mitogen connection fails with inaccessible home directory

### ISSUE THREAD

**Issue by opoplawski** [dw/mitogen#271]
on some of our machines the home directory of the user running ansible is not accessible.  This breaks with mitogen, but not with stock ansible.  I get:
```
[pid 21494] 08:55:56.259618 D mitogen: mitogen.ssh.Stream('local.21520').connect(): child process stdin/stdout=62
[pid 21494] 08:55:58.670126 D mitogen: mitogen.ssh.Stream('local.21520'): received 'Could not chdir to home directory /home/orion-admin: Permission denied\n'
[pid 21494] 08:55:58.670608 D mitogen: mitogen.ssh.Stream('local.21520'): child process still alive, sending SIGTERM
[pid 21513] 08:55:58.672513 D mitogen: mitogen.core.Stream('unix_listener.21494').on_disconnect()
[pid 21494] 08:55:58.673007 D mitogen: mitogen.core.Stream('unix_client.21513').on_disconnect()
[pid 21513] 08:55:58.673017 D mitogen: Waker(Broker(0x7fc2b38a9110) rfd=13, wfd=14).on_disconnect()
HOST | UNREACHABLE! => {
    "changed": false,
    "msg": "SSH authentication is incorrect",
    "unreachable": true
}
```

**Comment by dw** [comment]
There are a variety of ways to fix this, but I've gone with the simplest for now, as I'm battling issues elsewhere! Latest master should hopefully solve your issue. The problem is that it's looking for an authentication failure, and 'permission denied' is the string signalling that.

I may investigate a libssh2 or similar connection method, heuristics like this are always a nightmare to keep working.

**Comment by opoplawski** [comment]
Seems to do the trick, thanks again!
