### ISSUE TITLE
Solution looking for a problem ?

### ISSUE THREAD

**Issue by jbrodriguez** [dw/mitogen#28]
There's a lot of great code in this repo.

Alas, this is the reason I've decided against the python route: too much infrastructure tinkering.

FWIW, rust, ocaml, haskell, golang generate native binaries that can be ssh'ed to a remote machine and just be done with it.

Sorry for the rant, just my 2 cents.

**Comment by dw** [comment]
About 70% of my income over the past decade has been due to Python used for infrastructure, often a choice that had little to do with me. You're entitled to your opinions of course, however a bug tracker is the wrong place for them, and besides, it's clear if you think mutating a remote host's filesystem by default is a sensible option for infrastructure software (as copying binaries around entails), I sadly doubt you have much meaningful experience in this problem space. Take care
