### ISSUE TITLE
Could Mitogen be merged into Ansible?

### ISSUE THREAD

**Issue by sieben** [dw/mitogen#328]
It's more of a general question about your project. If the speed improvements are so relevant. What prevent you to merge this into Ansible? Could your improvements be pushed upstream and integrated?

**Comment by RonnyPfannschmidt** [comment]
i believe it would be interesting and desirable if ansible would integrate the plugin, it would be a grave mistake if ansible took in mitogen as a whole

**Comment by sieben** [comment]
What would be needed to make a PR to ansible with this plugin?

**Comment by RonnyPfannschmidt** [comment]
i would suggest orchestrating a conversation between the ansible Product management and @dw first - presuming both parties would be interested in this

**Comment by dw** [comment]
The short answer is that a third party extension was the best short-medium term delivery method, to allow the code to evolve and gain mindshare. Sadly it also increasingly looks like the best long-term method, possibly leading to an eventual "reverse merge" (read: fork) when monkeypatches no longer suffice.

@RonnyPfannschmidt hits the nail on the head. The issue is not technical, it is people. Or if it is technical, it is some email client bug that prevents an entire team from initiating an objective design discussion absolutely necessary before anything like acceptable PRs could exist. So meanwhile I've chosen to adopt a strategy mirroring theirs -- fixing the problem by sticking my fingers in my ears and getting on with what I consider to be productive work, without wasting any on further failed attempts at conversation.

At some stage an innocent interaction can become shameful, and after months this youthful idealist got tired of playing the role of evil leprechaun trying to sprinkle black magic around a holy village, much to the horror of its wizened elders, who for the most part ran around assembling imaginary hurdles while screaming "demon!" at each possible turn. It's hard not to eventually begin taking offence, so I simply stopped trying.

Meanwhile if selling blindingly simple perf fixes was a failed endeavour, there will be a slew of  aneurysms and overworked local hospital crash teams when I finally reveal the feature work I intend to build on top. If hurdles and friction exist already for the basics, there is little hope of achieving my goals using the previous approach, and I'm fresh out of new ideas.

**Comment by RonnyPfannschmidt** [comment]
@dw btw - im vastly curious as to what you intend to build on top ^^

**Comment by dw** [comment]
Wait and see! :)

**Comment by sieben** [comment]
https://groups.google.com/forum/#!topic/ansible-devel/0b2FEt118s8
