### ISSUE TITLE
`Channel()` usage example request

### ISSUE THREAD

**Issue by svinota** [dw/mitogen#329]
Is there any simple `Channel()` usage example — how to instantiate it on the remote side, what to use as  the handles, how to connect the local and the remote `Channel()` instances?

**Comment by dw** [comment]
Channel dates back to the earliest versions of the library, and actually I have never had a use for it that wasn't better served by `Sender` and `Receiver`. It is missing a crucial feature, where those handles are wired up for you.

I keep putting it off, because it's not clear where that feature should live -- part of the serialization (serializer that generates IO? Yuck!), as a wrapper function (yuck -- also the serializer doesn't permit pickling function references directly), or as a feature of the CALL_FUNCTION dispatcher.

There is a final problem: unlike Sender which has a very obvious semantic when serialized and sent to a remote node, with channel, if that node decides to serialize the same object and send it to a *third* participant, what should happen? Since it's supposed to be a pair of unidirectional queues, there is no place for any third or fourth participant.

In cases where I thought I need this, it turned out multiple sender/receiver combinations worked fine, albeit the result is more fiddly code-wise, semantically it is easy to follow.

You will likely recoil in horror at the example below, and the library could definitely use some higher level APIs for tidying it up, but I just haven't needed one yet. Suggestions welcome!

Example:

````

# master

# This receiver has a serialized Sender delivered on it, which is configured to
# deliver to the receiver in the child listening for commands. It should only
# receive once.
command_chan_recv = mitogen.core.Receiver(router, persist=False)

# This receiver gets regular updates from the child.
report_recv = mitogen.core.Receiver(router)


child.call(
    report_stuff_while_waiting_for_new_commands,
    command_chan_sender=command_chan_recv.to_sender(),
    report_sender=report_recv.to_sender(),
)

# Wait for the child to tell us how to send it commands.
command_sender = command_chan_recv.get()

# Send initial command
command_sender.send('foo')

while True:
    # Do stuff (e.g. sleep on multiple children with mitogen.select.Select(),
    # business logic, etc.)

    # In this case just block waiting for the single child.
    data = report_recv.get()
    print('Child reported something:', data)

    print('Now telling child to report on something else)
    command_sender.send('bar')




# child

@mitogen.core.takes_router
def report_stuff_while_waiting_for_new_commands(command_chan_sender, report_sender, router):
    # Make a receiver to receive commands.
    command_recv = mitogen.core.Receiver(router)

    # give the master a reference to it.
    command_chan_sender.send(command_recv.to_sender())

    # now loop waiting for commands and generating reports
    for cmd in command_recv:
        print('got command! ', cmd)
        data = do_report(cmd)
        print('sending report to master', data)
        report_sender.send(data)
````

**Comment by svinota** [comment]
Yep! That's exactly what I need.

Before the answer I tried to establish the channel between the child and the parent, and ended up with that code:
```python
import mitogen
import mitogen.utils


@mitogen.core.takes_econtext
def my_first_function(econtext):
    ch = mitogen.core.Channel(econtext.router, econtext.router._context_by_id[0], 1, 1)
    ch.send("test")
    return True


def main(router):
    ssh = router.ssh(hostname='192.168.122.100', username='test')
    ch = mitogen.core.Channel(router, ssh, 1, 1)
    call = ssh.call_async(my_first_function)
    print(ch.get().unpickle())
    print(call.get().unpickle())


if __name__ == '__main__':
    mitogen.utils.log_to_file('mitogen.log')
    mitogen.utils.run_with_router(main)
```

But I didn't get what the handles are, so just put there `1`. And if you're going to abandon `Channel()`, I'd better to use the way with `Sender`/`Receiver`.

Thanks a lot, it really solves all that I need :)

**Comment by svinota** [comment]
I don't close the issue, as I'll try to reflect this in the docs the next week and provide a PR.

**Comment by dw** [comment]
I have two ideas for a replacement for Channel, but delaying playing with it until I can start on the next development series of the Ansible extension, which will need one or both of them:

* "Pipe" abstraction, which uses some as-yet unknown magic to make it easy to stream between endpoints without having to do the plumbing yourself.

* "Scoreboard" abstraction, which is a silly name, but the name I'm using so far ;)  A distributed table that supports hierarchical update/subscription/broadcast.

Pipe is the closest thing to what channel wanted to be, but I'm still thinking about how it would work. I'm not averse to adding new core.py code to cope with wiring things up. Eventually the library will need to be easy to use, and that means lots of new code to hide the guts ;)

**Comment by dw** [comment]
I'm closing this as it was mostly an assistance request, however feel free to reopen if you have further queries or consider the issue a bug. Note that for quick ad-hoc questions, some users and developers are available on the [#mitogen](https://webchat.freenode.net/?channels=mitogen) channel on the FreeNode IRC network. Thanks!
