### ISSUE TITLE
Lots of empty directories left in /tmp

### ISSUE THREAD

**Issue by opoplawski** [dw/mitogen#397]
ansible 2.7.0
mitogen git ad44ad16f1210d00bb272f6436392099458d2aab (Oct 3)
Scientific Linux 7.5

After running I end up with lots of empty directories left in tmp:
```
# ls /tmp
ansible_mitogen_action_00d7fa93f3318247/
ansible_mitogen_action_022c07affc309838/
ansible_mitogen_action_04051aa8ca3426fd/
ansible_mitogen_action_0466508584120711/
ansible_mitogen_action_096ed9293d5e3dfd/
ansible_mitogen_action_09e4c74ad9a2b697/
ansible_mitogen_action_0ca8f3c04161db42/
....
```

**Comment by opoplawski** [comment]
Perhaps a side effect of using:
```
remote_tmp     = /tmp
```
?

**Comment by opoplawski** [comment]
Nope, without it I get lots in /root/.ansible/tmp, including a:
```
ansible-local-1513usmJRK/
```

**Comment by dw** [comment]
The problem was due to removing duplicate data appearing in multiple places. I forgot that the default Ansible behaviour is to reset that "shell.tmpdir" behaviour after remove is called. Fixed and test added for it.

Thanks a ton for reporting this! Hopefully will have an interim 0.2.4 release out perhaps by end of day.
