### ISSUE TITLE
Maximum message size exceeded on su in python3.7.1

### ISSUE THREAD

**Issue by syntonym** [dw/mitogen#437]
Trying to use `router.su`  leads me to the following error message on python 3.7.1:

`E mitogen: Maximum message size exceeded (got 1768910423, max 134217728)`

I tested against 0.2.0, 0.2.1, 0.2.2, 0.2.3 from pypi, and the current master branch (22de7f0), all with the same result. On python version 2.7.15 the same code does not through this error (only tested against 22de7f0).

su from util-linux 2.33 and kernel 4.19.4.arch1-1.

Code used:
```
import mitogen.utils
import getpass

mitogen.utils.log_to_file()
@mitogen.utils.run_with_router
def main(router):
    router.enable_debug()
    router.su(username="syntonym", password=getpass.getpass())
```

**Comment by dw** [comment]
Looks like somehow something is printing into the stream past the point where it should exclusively be used by the parent and child. 1768910423 in hex is 0x696f6e57, which is ASCII, "ionW".

Can you recognize that string? It might be printed perhaps by something imported by sitecustomize.py, usercustomize.py, or perhaps it is a PAM module invoked by su or similar.

Since bootstrap is completed, it seems more likely the corruption is by something within the Python interpreter, rather than PAM or bash or something.

Regardless, this is a bug because that error could be improved. It is a simple matter to include, say, 2 signature bytes in every message, and if they are incorrect, produce a more descriptive error message including a dump of whatever string was actually received.

Thanks for reporting this!

**Comment by dw** [comment]
Grepping /usr/lib/python3.6, I see "ionW" appears a lot in "DeprecationWarning" :) I will test more locally, looks like it is definitely a Mitogen issue

**Comment by dw** [comment]
I've got an Arch VM matching yours and I cannot reproduce this deprecation warning :S  Does the target or source user have some bashrc perhaps, that sets some environment variables?

I'm thinking perhaps the warning is relating to a locale setting in the environment, i.e. LC_ALL, LANG etc., or some similar mechanism

**Comment by dw** [comment]
possibly related: #399

**Comment by dw** [comment]
I managed to reproduce it. It is indeed due to #399, and it only impacts su because su redirects its stderr into stdout in order to cope (IIRC) with FreeBSD.

**Comment by dw** [comment]
This is now on the master branch and will make it into the next release. To be updated when a new release is made, subscribe to https://www.freelists.org/list/mitogen-announce

I will open a separate ticket to improve the stream corruption error messages.

Thanks for reporting this!

**Comment by syntonym** [comment]
I tested the current HEAD version and can confirm that the bug is fixed. 

Thanks for the super quick bugfix! I did not expect such a quick answer, let alone a fix.
