### ISSUE TITLE
Failed to create a PTY. Operation not permitted [on CentOS7]

### ISSUE THREAD

**Issue by yhafri** [dw/mitogen#462]
I'm getting the following error when running my playbook to update a remote `CentOS7` machine
(the same playbook works perfectly well on all my `Ubuntu` instances).

```
  ____________
< PLAY [all] >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

 ________________________
< TASK [Gathering Facts] >
 ------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [centos7]: FAILED! => {"msg": "error occurred on host xxx.xxx.xxx.xxx: Failed to create a PTY: [Errno 1] Operation not permitted. It is likely the maximum number of PTYs has been reached. Consider increasing the 'kern.tty.ptmx_max' sysctl on OS X, the 'kernel.pty.max' sysctl on Linux, or modifying your configuration to avoid PTY use."}
        to retry, use: --limit @/Users/xxx/ansible/script/update.retry
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

centos7                 : ok=0    changed=0    unreachable=0    failed=1
```

My `CentOS7` instance has enough PTYs as you can see:
```
# sysctl kernel.pty.max
kernel.pty.max = 5120
```

Moreover, it's an idle machine. No service is running on it except the default ones.

My host config is:

1. *macOS* High Sierra `10.13.6`
2. *Mitogen* from GIT `master (ec05604)`
3. *Python*
```
$ python
Python 2.7.15 (default, Oct  2 2018, 11:47:18)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```
4. *Ansible* from `brew`
```
$ ansible --version 
ansible 2.7.5
  config file = /Users/xxx/.ansible.cfg
  configured module search path = ['/Users/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.5/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.1 (default, Nov 28 2018, 11:51:54) [Clang 10.0.0 (clang-1000.11.45.5)]
```
5. My `~/.ansible.cfg` is:
```
[ssh_connection]
retries=3
pipelining = True

[defaults]
timeout = 20
host_key_checking = False
ssh_args = -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ServerAliveInterval=60
strategy_plugins = ~/.ansible/plugins/mitogen/ansible_mitogen/plugins/strategy
strategy = mitogen_linear
``` 

> [ IMPORTANT ]
> if I disable `mitogen`, the playbook works well for `CentOS7` !!!

**Comment by dw** [comment]
Sorry for the extreme delay replying to this one. Can either of you confirm whether SELinux is enabled or not? Is there anything else about your configuration that might be considered 'non-default', say, are you logging in with an LDAP account or suchlike that might effect group memberships, etc.

**Comment by dw** [comment]
Would it be possible to include the output of these commands:

````
echo pty perms:
ls -ld /dev/ptmx /dev/pts `tty`
echo

echo user account perms:
id
echo

echo selinux:
getenforce
echo
````

Also if you can think of any security features that might be enabled on these servers that aren't enabled elsewhere.. different install script / admin team perhaps? etc.

Thanks again!

**Comment by dw** [comment]
The devpts mount is set with no 'gid=' option, therefore when the new PTY is allocated, the kernel gives it the GID of the process (1000). Something in Python or the C library does not like that, and wants to change its group to 5 (probably the 'tty' group, so "wall" and commands like that function), and that's the source of the error.

From looking at a uname() line in the log, and also the presence of multiple devpts mounts in the previous output, am I right in saying this is a container of some sort? What kind of container runtime created it?

Mitogen does not require the group to be changed on its PTYs, so this can definitely be worked around, I assume it is overzealous library code causing the problem. This issue in `rkt` looks like a very similar problem, the strace is basically the same: https://github.com/rkt/rkt/issues/2152

As for why it does not manifest with regular Ansible, that is because in that case, IIRC the whole SSH connection is started interactively, which means the SSH daemon sets up the PTY. This puts severe constraints on non-interactive use of the channel (e.g. buffer sizes for a PTY are tiny), and so Mitogen only allocates PTYs as needed and (ideally) only in cases where they are definitely required.

Does your Ansible configuration include a become password? If not, then that is a separate bug -- Mitogen should not be allocating a PTY at all in this case.

**Comment by dw** [comment]
The failing library code is [grantpt() in the C library](https://github.com/bminor/glibc/blob/80dfa298741800602a4d5f950e0ebf0f95b2f7cc/sysdeps/unix/grantpt.c#L96-L136), called by openpty() in the C library, called by os.openpty() in Python

**Comment by yhafri** [comment]
Thanks for the detailed explanations.

> From looking at a uname() line in the log, and also the presence of multiple devpts mounts in the previous output, am I right in saying this is a container of some sort? What kind of container runtime created it?

Yes, that's a [customer kernel](https://docs.ovh.com/ca/en/dedicated/updating-kernel-dedicated-server/) from a Cloud provider.

> Does your Ansible configuration include a become password? If not, then that is a separate bug -- Mitogen should not be allocating a PTY at all in this case.

Nope.  There is no `become password` in my config.

**Comment by dw** [comment]
[An entire LWN article dedicated to this very issue](https://lwn.net/Articles/688809/) :)

**Comment by yhafri** [comment]
Can you think of any solution/workaround?

**Comment by dw** [comment]
When you say it is a customer kernel, does it mean they have replaced the OVH-supplied kernel? CentOS 7 should have shipped with Linux 3.10, and unfortunately for us, the fix mentioned in the LWN article did not arrive until Linux 4.8.

If I understand things correctly, I think you are SSHing into a container whose magic `/dev/pts` filesystem is not configured correctly. This problem does not manifest on my local CentOS 7 VM, and indeed, only one `/dev/pts` mount is visible on that VM, so those extra mounts must be coming from some piece of software -- I assume a container manager program like LXC, LXD, or Docker, but perhaps there is another explanation so far we are missing.

Thanks for all your help so far. I will need to setup a reproduction for this in order to test a workaround. TTY handling code is very fragile, and if we are short-circuiting the C library to setup a TTY ourselves, it would be nice to limit it only to this particular case. This may take some more time over the weekend.

I remembered the reason sudo is always called with a TTY -- it is because many sudo configurations ship with an incredibly pointless `requiretty` option enabled. It is pure security theatre. Without it, no password can be typed, and even when no password is required, sudo will still refuse to run. It might be possible to detect `requiretty`'s existence, but not without creating authentication failures in the system log. So it is better we try to fix PTY allocation instead.

Thanks again for your help

**Comment by yhafri** [comment]
> When you say it is a customer kernel, does it mean they have replaced the OVH-supplied kernel? CentOS 7 should have shipped with Linux 3.10, and unfortunately for us, the fix mentioned in the LWN article did not arrive until Linux 4.8.

Kernel version is `4.9.58`, so the issue should be fixed (>4.8).
```bash
$ uname -r
4.9.58-xxxx-std-ipv6-64
```

No rush @dw.  Tell me what I can do to help if/when needed.

**Comment by dw** [comment]
I managed to reproduce the problem on CentOS 7.5.1810 easily enough, but not in a satisfactory manner. On a clean install, it is sufficent to run `mount -t devpts none /dev/pts -oremount` to cause the `gid` option to be unset, at which point Python will behave as documented in this bug.

When the gid parameter is incorrect, programs running as root, such as SSHd, will be able to call openpty() successfully, but non-root programs like Python will fail.

On investigating, Dracut, the initramfs framework in CentOS 7.5, is responsible for setting up the host's /dev/pts, and it does this with the correct options hard-wired. So it is some extra package or configuration on these machines causing the problem after initramfs has already run.

I have scoured Red Hat's bugzilla and could find no decisive reference to a single package that could cause it, but did find some interesting hints. [In this ticket](https://bugzilla.redhat.com/show_bug.cgi?id=1000018) the user had modified `/etc/fstab` of Fedora 19 by removing the `/dev/pts` line, causing it to be mounted with default arguments. However on my CentOS 7.5 install, /dev/pts mounting is explicitly handled in initramfs, and no `/dev/pts` line.

It is possible even if initramfs is setting things up correctly, that a **redundant line** in `/etc/fstab` is causing the options to be reset later during boot. Does your `/etc/fstab` have an entry for `/dev/pts`? It should not.

Finally the presence of multiple `/dev/pts` in the output of mount is a huge signal that something is messing with these after boot, that may not be part of the core system. The only software I know of that needs to do this are container runtimes like Docker, LXC, LXD, systemd-nspawn, or rkt -- is there anything like that running on these machines?

While it is possible to add code to Mitogen to handle this case, the more I investigate the issue, the more it feels like a configuration error somewhere. I would like to find understand the root cause of that configuration error -- if it is in a common package, or a common misconfiguration, then it makes sense to add the code. But if it is rare, then a better option would be to fix the error and update Mitogen's failure message to explain what is likely broken.

Thanks again! This is a fun one :)

**Comment by dw** [comment]
After more Google searches, I'm sufficiently convinced there are enough broken systems around that this merits a code change.

I have created a new branch containing a fix. Would it be possible to run Mitogen from the [issue462 branch](https://github.com/dw/mitogen/tree/issue462) to ensure both issues have abated? Pretty sure this fixes @yhafri's case, but it would nice to confirm @sboisson's issue is identical.

````
git clone -b issue462 https://github.com/dw/mitogen/
````

**Comment by yhafri** [comment]
Awesome. The fixed in branch `issue462` worked.
I only got these 2 errors:

```
ERROR! [pid 68929] 22:58:54.282173 E mitogen.ctx.ssh.91.121.153.46:51789: mitogen: RouteMonitor(): received DEL_ROUTE for 2007 from mitogen.sudo.Stream(u'sudo.root'), expected mitogen.core.Stream('parent')
ERROR! [pid 68929] 22:58:54.283527 E mitogen.ctx.ssh.91.121.153.46:51789.sudo.root: mitogen: RouteMonitor(): received DEL_ROUTE for 2007 from mitogen.fork.Stream(u'fork.25829'), expected mitogen.core.Stream('parent')
```

**Comment by yhafri** [comment]
After Googling a little bit, i found [this](https://medium.com/@sbarnea/why-ansible-ignore-errors-is-evil-500fb6e81229):

Thus, switching from `ignore_errors: True` to `failed_when: False` solved the 2 errors unrelated to mitogen IMHO.
```

**Comment by dw** [comment]
Those errors should have been fixed already :) They will definitely be gone for 0.2.4, there is another ticket open for it. You can safely ignore them

**Comment by yhafri** [comment]
Thanks a mill and have a great weekend.
Long live to `mitogen` !!!

**Comment by dw** [comment]
Thanks so much for your help :)   I will keep the ticket open until @sboisson can confirm the fix.

**Comment by dw** [comment]
I merged this down to master in order to work on other things -- @sboisson please reopen if you're still having the problem.

---

This is now on the master branch and will make it into the next release. To be updated when a new release is made, subscribe to https://www.freelists.org/list/mitogen-announce

Thanks for reporting this!

**Comment by sboisson** [comment]
Sorry for the delay, I was away for holidays. I change works for me too! (tested with branch master)
