### ISSUE TITLE
Mitogen does not support Ansible 2.8 yet

### ISSUE THREAD

**Issue by opoplawski** [dw/mitogen#587]
* Which version of Ansible are you running? 2.8rc3
* Is your version of Ansible patched in any way? no
* Are you running with any custom modules, or `module_utils` loaded? yes

* Have you tried the latest master version from Git? yes - this is with latest master
* Mention your host and target OS and versions

Host - EL7.6

* Mention your host and target Python versions

python 2.7.5

```
PLAY [webfilter*] **********************************************************************************************************************************************************
[mux  9691] 17:21:18.993407 D mitogen: mitogen.service.Pool(0x7f124f022190, size=32, th='MainThread'): initialized
[mux  9691] 17:21:18.996991 D ansible_mitogen.process: Service pool configured: size=32

TASK [Gathering Facts] *****************************************************************************************************************************************************
task path: /export/home/orion-admin/ansible-boulder/playbooks/e2guardian.yml:2
Sunday 12 May 2019  17:21:19 -0600 (0:00:00.185)       0:00:00.185 ************ 
ERROR! Unexpected Exception, this is probably a bug: expected string or buffer
the full traceback was:

Traceback (most recent call last):
  File "/bin/ansible-playbook", line 110, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 123, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 170, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 249, in run
    play_return = strategy.run(iterator, play_context)
  File "/export/home/orion-admin/ansible-boulder/mitogen/ansible_mitogen/strategy.py", line 254, in run
    lambda: run(iterator, play_context)
  File "/export/home/orion-admin/ansible-boulder/mitogen/mitogen/core.py", line 561, in _profile_hook
    return func(*args)
  File "/export/home/orion-admin/ansible-boulder/mitogen/ansible_mitogen/strategy.py", line 254, in <lambda>
    lambda: run(iterator, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 306, in run
    self._queue_task(host, task, task_vars, play_context)
  File "/export/home/orion-admin/ansible-boulder/mitogen/ansible_mitogen/strategy.py", line 229, in _queue_task
    class_only=True,
  File "/export/home/orion-admin/ansible-boulder/mitogen/ansible_mitogen/strategy.py", line 98, in wrap_connection_loader__get
    return connection_loader__get(name, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 557, in get
    path = self.find_plugin(name, collection_list=collection_list)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 506, in find_plugin
    plugin = self._find_plugin(name, mod_type=mod_type, ignore_deprecated=ignore_deprecated, check_aliases=check_aliases, collection_list=collection_list)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 395, in _find_plugin
    if (is_collection_ref(name) or collection_list) and not name.startswith('Ansible'):
  File "/usr/lib/python2.7/site-packages/ansible/utils/collection_loader.py", line 298, in is_collection_ref
    return bool(_collection_qualified_re.match(candidate_name))
TypeError: expected string or buffer
[mux  9691] 17:21:19.052346 D mitogen: Waker(Broker(0x7f124f00fa10) rfd=6, wfd=8).on_disconnect()
[mux  9691] 17:21:19.052735 D mitogen: Router(Broker(0x7f124f00fa10)): stats: 0 module requests in 0 ms, 0 sent (0 ms minify time), 0 negative responses. Sent 0.0 kb total, 0.0 kb avg.                             
```

**Comment by ulrichSchreiner** [comment]
this happens with the 2.8 release too

**Comment by dcarrillo** [comment]
For what it's worth, I get the same results with Python 3.7.3 and ansible 2.8.0

**Comment by dw** [comment]
Some initial work has started in the `issue587` branch, but it's far from complete. Summary of the work so far:

- Support for the obsolete config system has been significantly dropped in 2.8, meaning that Connection plugins and (new) Become plugins are responsible for looking up their own configuration values. This is progress, but it puts Mitogen in a tough situation since we want to maintain support for Ansible 2.3/2.4, where the new config system was either non-existent or in a very immature state.

  I will not drop support for 2.3 since the extension has 2.3 existing users, and newer Ansibles broke the syntax of working configurations.

  It seems the option here is to internally reimplement the new configuration system. That's not a great deal of work, and in fact it's an opportunity to further improve the robustness of connection delegation (by merging the config lookup method for 'direct connect' and 'delegated connection'). I also like this option because upstream's new config system regularly features quite high up in profiler output, and so there is potential to improve on its performance.

- Support for become plugins. This sticker here is supporting connection delegation -- it must be possible for an intermediary machine to call back into the become plugin API hosted on the master machine. This again, isn't a huge amount of work, but I've been putting it off to avoid reimplementing the whole thing twice.

  There is currently a very large `stream-refactor` branch that introduces "internally asynchronous" connect. This is a major design change with many benefits, and I'd like to land it first before addressing become plugins, because the become plugin implementation will also need to be asynchronous to match the new implementation.

AFAIK it should be possible to cut a release without become plugin support, and few users will notice the difference, but for now the config system issue is a blocker. It should only take a few days to implement, but I'm short on time for the coming months.

**Comment by dw** [comment]
If anyone wants to give `issue587` branch a tyre kick - it would be very useful :)

Some internal variables have changed semantic (so CI is still broken), but I overestimated how much compat code has been removed. It's possible this will be a much quicker success than expected

**Comment by dw** [comment]
Bare minimum implementation seems to be done now -- please open fresh issues for anything you bump into, but CI is passing so I'm happy :)

-----

This is now on the master branch and will make it into the next release. To be updated when a new release is made, subscribe to https://www.freelists.org/list/mitogen-announce

Thanks for reporting this!

**Comment by opoplawski** [comment]
Thanks for working on this.  I'm running into #590 now, so following that.

**Comment by dw** [comment]
Hi @opoplawski, there is now a workaround for #590 on current master. Note CI is currently only set up for 2.8.0 Py2.7/Py3.5 host -> Py2.7 interpreter, so another variant of #590 may be lurking in the -> Py3.5 interpreter direction

**Comment by varac** [comment]
Thanks for fixing this - is there any planned release so we can profit from this fix using pip install ?

**Comment by dw** [comment]
@varac a 2.8-compatible release is coming real soon. I'm pushing 2 big branches as part of the same release, as they're both related to 2.8 features. That means we'll have one interim featureful release with functional 2.8 support, and all the features in place needed for complete 2.8 support in a subsequent 'mostly fixes only' followup release.

**Comment by armenr** [comment]
Hey there! Thanks for all of your work on this. Anything released for 2.8 yet? :)

**Comment by makkus** [comment]
@armenr : https://mitogen.networkgenomics.com/changelog.html#v0-2-8-2019-08-18

**Comment by armenr** [comment]
Roger that! @makkus - thanks for the ref. All I had to do was RTF to know it. My bad, and thanks for all your excellent work!
