### ISSUE TITLE
BUSY FOR COMING MONTHS

### ISSUE THREAD

**Issue by dw** [dw/mitogen#588]
Apologies for delay in sorting out the tickets (most of them are straightforward!), and most important of all Ansible 2.8 support, I'm on another project for the coming months. Please continue filing tickets as normal and try to include as much detail as possible! Thanks

----

# For Ansible 2.8 support, use current master branch

**Comment by vladp** [comment]
Hello, I am just newbie at devops and at ansible.
Wanted to stop by to thank you for making mitogen.

Besides performance improvement (which at this point of learning, are not that important to me),
mitogen helped me to understand and reason about Ansible's execution flow at a more intuitive leve.

For example, in test env I have many hosts pointing to the same machine.
One of roles is to update package /distro on all the machines.
Without Mitogen, I was getting constant 'dpkg lock errors' because ansible
was reaching out to logically different, but physically same hosts concurrently.

With mitogen, it seems to 'normalize' and reduce hosts and tasks to properly
constrained minimum and execute hosts tasks related for one host in proper sequence.

may be this is a small example of mitogen capabilities, but to me it was 
it was refreshing.

thx again.

**Comment by xcambar** [comment]
Thanks for clarifying the situation.

Just to be extra-super-duper clear: will you still be able to dedicate some time to mitogen while you're busy with the other project(s)? Especially about releasing new versions to maintain compatibility with the latest ansible.
If not, will you delegate?

**Comment by dw** [comment]
@xcambar basic support for 2.8 is probably easy, and almost certainly PRable for a new contributor -- just knock down the exceptions using any means necessary, even if it means making a temporary mess. A hacky master branch is better than a nonexistent release ;) Real support for 2.8 requires non-trivial knowledge of the Ansible tree and Mitogen tree, because we need to add a whole new mechanism to let become plugins operate remotely. I know how this needs to work, but I want to land async connect first -- itself a major piece of functionality. Quite happy to see contributions for the former approach ,but the latter approach requires a more context and comms than I have resources to support

As for 'will you delegate', the better question to ask is probably 'will you at least review the diffs before clicking merge' ;)  The trouble is finding willing and capable resource!
