### ISSUE TITLE
Bug in sample app on doc

### ISSUE THREAD

**Issue by sfermigier** [dw/mitogen#606]
On <https://mitogen.networkgenomics.com/index.html> the `install_app.py` example gives an error:

```
  File "....py", line 25, in main
    context = mitogen.ssh.connect(broker, sys.argv[1])
AttributeError: module 'mitogen' has no attribute 'ssh'
```

**Comment by dw** [comment]
That's unintentionally hilarious.. the bug has been there for so long that the API changed to 'router.ssh()', and now there it is planned to return it to 'ssh.connect()'. I'm unfortunately quite blind to the state of the documentation just from keeping on top of development and testing

If you are playing with the library itself (as opposed to the Ansible extension), beware the fakessh component is currently broken and there is no plan to fix the current design. It needs a complete rewrite to add flow control, but I don't want to add Yet Another flow control mechanism, so that rewrite is deferred until a generic design exists.

The getting started guide is still in a state of disrepair. I have actually sat down a few times recently to finally pad it out. It might be worth scanning all the notes for that chapter from https://github.com/dw/mitogen/issues/451

Thanks for reporting this!

**Comment by dw** [comment]
The example is corrected on the docs-master branch. It will reach the real master next time a merge is done for some actual code (docs-master exists to avoid 20 minute CI delays for spelling mistakes).

Thanks again

**Comment by dw** [comment]
Also beware if you're playing, might be wise to stick to the last stable release. 2 huge branches reached master this week, it's made a mess of CI and at least one race has appeared on OS X
