### ISSUE TITLE
master: Why does create_child() call os.dup() in the parent process?

### ISSUE THREAD

**Issue by moreati** [dw/mitogen#70]
In [`mitogen.master.create_child()`](https://github.com/dw/mitogen/blob/master/mitogen/master.py#L101-L115) why does the parent process return a duplicate of parentfp's descriptor (i.e. `os.dup(parentfp.fileno())`) rather than just `parentfp.fileno()`?

Again my lack of POSIX fu leaves me on shaky ground, but the  fd that is unclosed and unreferenced (once the function returns) feels like a resource leak.

**Comment by dw** [comment]
It's because when parentfp goes out of scope, it closes the underlying file
descriptor, and we have no means of tracking objects associated with file
descriptors. Therefore it's easier to just make a self-managed duplicate.

It would be possible to teach Side, and all code leading to Side to work in
terms of file-like objects so this wasn't necessary, but the only use for
that would be to get a reference-counted fd lifetime, which doesn't really
even give us much in terms of ensuring the fd is always closed correctly in
places e.g. like on PyPy. The file object methods are also pretty much
useless for IO since we do our own asynchronous buffering and non-blocking
calls, etc.

​
