### ISSUE TITLE
master: cfmakeraw() sets different flags to those documented for termios(3)

### ISSUE THREAD

**Issue by moreati** [dw/mitogen#71]
The differences are

1. mitogen ~~adds~~ clears `IXOFF` in `oflag`
1. mitogen ~~adds~~ clears `ECHOE` in `lflag`
1. mitogen additionally overwrites `iflag`, `oflag`, and `lflag` with `0`

According to [termios(3)](https://linux.die.net/man/3/termios) the glibc function performs

```c
c_iflag &= ~(IGNBRK | BRKINT | PARMRK | ISTRIP | INLCR | IGNCR | ICRNL | IXON);
c_oflag &= ~(OPOST);
c_lflag &= ~(ECHO | ECHONL | ICANON | ISIG | IEXTEN);
c_cflag &= ~(CSIZE | PARENB);
c_cflag |= CS8;
```
mitogen's `cfmakeraw()` currently performs

https://github.com/dw/mitogen/blob/c503706f96a5bf5074d8c807b0873f869f232675/mitogen/master.py#L132-L143

As usual I don't know how much of this is intentional vs accidental.

Edit 2017-12-03 Corrected add -> clear

**Comment by dw** [comment]
Good catch! Per the comment I added a few days ago, that function is
somehow horribly wrong. From what I remember while writing it, it no longer
does quite what cfmakeraw() was supposed t do. For example we need to
disable "local echo" (ECHOE), otherwise when we write a frame to our TTY,
it will immediately appear as a duplicate when we next read from the TTY.
Really we want the TTY to behave as close to a pipe as possible, the only
use for the TTY is to allow interactive input of the SSH password, and for
sudo, to trick its idiotic broken-by-design requiretty flag into permitting
a login.

I confess the TTY layer, despite having worked with it repeatedly over the
past decade, still scares the hell out of me :)  These flags, btw, map to
different semantics depending on the TTY driver. I haven't the first clue
of where those differences lie, but in any case, we're always targetting
the Linux or BSD pty driver, so we probably don't need to worry about that.

Really there isn't much to do for this one except go through each,
flag-by-flag, and figure out whether they have any observable effect on IO,
and if not, either just disable as many flags as possible, or maybe just
avoid twiddling as many flags as possible away from their raw/cooked mode
defaults. (We definitely need raw mode -- cooked mode causes things like ^W
and ^U to edit the current line when a byte with that value is written by
the library, and ^C to generate SIGINT!)

The other concern with the flags is how they impact sudo and ssh.  When I
was hacking this, I was testing continuously with real sudo to a real
alternative account on my local machine. There's probably no alternative
way to build confidence in what these flag changes do except real testing
(or reading up on ancient UNIX stuff!)

Aah, one final note.. BSD cfmakeraw() and Linux cfmakeraw() may be
documented as doing different things. These functions were written in a
time when "UNIX" literally meant a product from AT&T, and common semantics
beyond the existence of open() and close() system calls had yet to be
established ;)  So would not be surprised if my MacOS man pages for
ckmakeraw() do not match yours -- this stuff is prehistoric

**Comment by moreati** [comment]
[FreeBSD's cfmakeraw()](https://github.com/freebsd/freebsd/blob/82974662ad9f9ece5f8374d2c898e83bd03aece9/lib/libc/gen/termios.c#L172-L179) performs

```c
t->c_iflag &= ~(IMAXBEL|IXOFF|INPCK|BRKINT|PARMRK|ISTRIP|INLCR|IGNCR|ICRNL|IXON|IGNPAR);
t->c_iflag |= IGNBRK;
t->c_oflag &= ~OPOST;
t->c_lflag &= ~(ECHO|ECHOE|ECHOK|ECHONL|ICANON|ISIG|IEXTEN|NOFLSH|TOSTOP|PENDIN);
t->c_cflag &= ~(CSIZE|PARENB);
t->c_cflag |= CS8|CREAD;
t->c_cc[VMIN] = 1;
t->c_cc[VTIME] = 0;
```

**Comment by moreati** [comment]
I'm going to take a wander through the OpenSSH code to see when it calls cfmakeraw(), and what other things it does.

**Comment by dw** [comment]
Thanks for looking at this!

Just a few things to guide you, and also places where I'm shaky w.r.t. how
ttys do or are supposed towork..

- There is the concept of the tty's session, and also its foreground group.
I have a mental TODO to check if we need to call setpgrp() or setsid()
somewhere. I think it might need to be called in the child before execcing
sudo or ssh, not sure.  Not sure because I can't remember what effect it
has. It impacts at least signal delivery. If we set it one way, then CTRL+C
to the mitogen-using process won't propagate, but (some other effect I
don't understand), but if we do it the other way, Mitogen must explicitly
kill the sudo/ssh child when it receives CTRL+C (which entails installing a
signal handler from a library, I def don't want to go that route), but (yet
some other effects I don't understand) :)

- The flags must be set so that bytes aren't interpreted whatsover. No
XON/XOFF, no CTRL+C, CTRL+U, etc.

- The flags can be set differently on the master and slave side of the pty.
I have no idea how or why or which way this works. I think the slave gets a
default set of flags, and we don't touch those yet.. and ssh/sudo seem
happy to run with them

- When you're looking at SSH, don't forget it's explicitly wanting to
configure things so that the TTY works nicely for a human. We want the
opposite

**Comment by dw** [comment]
Aah, and one super important final note about this TTY stuff. I think on
BSD variants, there is some weird rule where the first program to use the
slave side of the pty implicitly causes one of those setsid/setpgrp calls.
On Linux (and e.g. Solaris I think), it must be done explicitly.

**Comment by moreati** [comment]
Summary so far
- `Y` flag is applied `&= ~(...|FLAG|...)
- `O` flag is applied `|= (...|FLAG|...)
- `*` flag is subject to `#ifdef` 

|         |         | Mitogen | glibc | FreeBSD | OpenBSD | OpenSSH | Paramiko |
|---------|---------|:-------:|:-----:|:-------:|:-------:|:-------:|:--------:|
| c_iflag | BRKINT  |    Y    |   Y   |    Y    |    Y    |         |     Y    |
|         | ICRNL   |    Y    |   Y   |    Y    |    Y    |    Y    |     Y    |
|         | IGNBRK  |    Y    |   Y   |    O    |    Y    |         |          |
|         | IGNCR   |    Y    |   Y   |    Y    |    Y    |    Y    |          |
|         | IGNPAR  |         |       |    Y    |         |    O    |          |
|         | IMAXBEL |         |       |    Y    |    Y    |         |          |
|         | INLCR   |    Y    |   Y   |    Y    |    Y    |    Y    |          |
|         | INPCK   |         |       |    Y    |         |         |     Y    |
|         | ISTRIP  |    Y    |   Y   |    Y    |    Y    |    Y    |     Y    |
|         | IUCLC   |         |       |         |         |    Y*   |          |
|         | IXANY   |         |       |         |         |    Y    |          |
|         | IXOFF   |         |       |    Y    |         |    Y    |          |
|         | IXON    |    Y    |   Y   |    Y    |    Y    |    Y    |     Y    |
|         | PARMRK  |    Y    |   Y   |    Y    |    Y    |         |          |
|         |         |         |       |         |         |         |          |
| c_oflag | IXOFF   |    Y    |       |         |         |         |          |
|         | OPOST   |    Y    |   Y   |    Y    |    Y    |    Y    |     Y    |
|         |         |         |       |         |         |         |          |
| c_lflag | ECHO    |    Y    |   Y   |    Y    |    Y    |    Y    |     Y    |
|         | ECHOE   |    Y    |       |    Y    |         |    Y    |          |
|         | ECHOK   |         |       |    Y    |         |    Y    |          |
|         | ECHONL  |    Y    |   Y   |    Y    |    Y    |    Y    |          |
|         | ICANON  |    Y    |   Y   |    Y    |    Y    |    Y    |     Y    |
|         | IEXTEN  |    Y    |   Y   |    Y    |    Y    |    Y*   |     Y    |
|         | ISIG    |    Y    |   Y   |    Y    |    Y    |    Y    |     Y    |
|         | NOFLSH  |         |       |    Y    |         |         |          |
|         | PENDIN  |         |       |    Y    |         |         |          |
|         | TOSTOP  |         |       |    Y    |         |         |          |
|         |         |         |       |         |         |         |          |
| c_cflag | CSIZE   |    Y    |   Y   |    Y    |    Y    |         |     Y    |
|         | PARENB  |    Y    |   Y   |    Y    |    Y    |         |     Y    |
|         | CS8     |    O    |   O   |    O    |    O    |         |     O    |
|         | CREAD   |         |       |    O    |         |         |          |
|         |         | Mitogen | glibc | FreeBSD | OpenBSD | OpenSSH | Paramiko |

**Comment by moreati** [comment]
> The differences are
> 1. mitogen clears `IXOFF` in oflag

`IXOFF` is not listed by termios(3) as applicable for `oflag`. `IXOFF == 2**12` doesn't appear to clash with any valid `oflag` constants.

> 2. mitogen clears `ECHOE` in lflag

ECHOE is cleared by Mitogen, OpenSSH and OpenBSD: disabling "the ERASE character erases the preceding input character, and WERASE erases the preceding word."

> 3. mitogen additionally overwrites iflag, oflag, and lflag with 0

WIthout this override, then on Ubuntu Linux 17.10 with Python 2.7 the result would be
```pycon
>>> old = termios.tcgetattr(sys.stdin.fileno())
>>> new = makecfraw(old)
>>> [bin(i) for i in old[:4]]
#iflag                oflag    cflag         lflag
['0b0100 0001 0000 0000', '0b101', '0b1011 1111', '0b1000 1010 0011 1011']
>>> [bin(i) for i in new[:4]]
['0b0100 0000 0000 0000', '0b100', '0b1011 1111', '0b0000 1010 0010 0000']
```
So by setting these four fields to 0 we are disabling the flags at positions

iflag:
    15
oflag:
    3
cflag:
    1
    2
    3
    4
    5
    6
    8
lflag
    6
    10
    12
```

**Comment by moreati** [comment]
If I've done my octal correctly, then by setting iflag, oflag, & lflag to 0 we are additionally disabling

```
c_iflag		0o00040000
	IUTF8	0o00040000

c_oflag		0o00000004
	ONLCR	0o00000004

c_lflag		0o00000277
	ECHOE	0o00000020
	NOFLSH	0o00000200
	ECHO	0o00000010
	ISIG	0o00000001
	ICANON	0o00000002
	XCASE	0o00000004
	ECHOK	0o00000040
```

**Comment by moreati** [comment]
Inspecting the source code of Python's `termios.tcsetattr()`. I noted (a) it returns None, (b) it raises an exception if the corresponding libc function returns `-1`.

In termios(3) it is noted that
> tcsetattr() returns success if _any_ of the requested changes could  be  successfully  carried  out.  Therefore, when making multiple changes it may be necessary  to follow this call with a further call to tcgetattr() to check that all changes have been performed successfully

mitogen does not currently do this.

**Comment by moreati** [comment]
Adhoc code to test whether all flags set/cleared by `disable_echo()`/`cfmakeraw()` are accepted by the tty layer:

```python
def disable_echo(fd):
    old = termios.tcgetattr(fd)
    req = cfmakeraw(old)
    flags = (
        termios.TCSAFLUSH |
        getattr(termios, 'TCSASOFT', 0)
    )
    termios.tcsetattr(fd, flags, req)
    new = termios.tcgetattr(fd)
    with open('/tmp/disable_echo', 'a') as f:
        f.writelines([
            'fd=%0d old i=0o%08o o=0o%08o c=0o%08o l=0o%08o\n'
            % (fd, old[0], old[1], old[2], old[3]),
            'fd=%0d req i=0o%08o o=0o%08o c=0o%08o l=0o%08o\n'
            % (fd, req[0], req[1], req[2], req[3]),
            'fd=%0d new i=0o%08o o=0o%08o c=0o%08o l=0o%08o\n'
            % (fd, new[0], new[1], new[2], new[3]),
        ])
```

the answer (on Ubuntu 17.10) appears to be yes

```
fd=12 old i=0o00002400 o=0o00000005 c=0o00000277 l=0o00105073
fd=12 req i=0o00000000 o=0o00000000 c=0o00000277 l=0o00000000
fd=12 new i=0o00000000 o=0o00000000 c=0o00000277 l=0o00000000
fd=13 old i=0o00000000 o=0o00000000 c=0o00000277 l=0o00000000
fd=13 req i=0o00000000 o=0o00000000 c=0o00000277 l=0o00000000
fd=13 new i=0o00000000 o=0o00000000 c=0o00000277 l=0o00000000
```
