### ISSUE TITLE
ansible_mitogen strategy not installed by pip

### ISSUE THREAD

**Issue by MartinNowak** [dw/mitogen#85]
Using pip 9.0.1, only the following ansible_mitogen modules are installed.

```
site-packages/ansible_mitogen/__init__.py
site-packages/ansible_mitogen/helpers.py
site-packages/ansible_mitogen/mixins.py
```

**Comment by arbabnazar** [comment]
@dw I second @MartinNowak. It didn't install properly

**Comment by dw** [comment]
I've put it on PyPI as a one-off for testing. The problem with it being on PyPI is that it tends to generate tons of bug reports from people who think the software is ready when it is not (I've seen this before :) ).

**Comment by dw** [comment]
Aah, I see I didn't read the bug report correctly -- this isn't about PyPI, it was about setup.py :) Well that is fixed now too. Sorry!

**Comment by arbabnazar** [comment]
@dw Thanks it's working fine and here are some results that might be of your interest:

**With Mitogen**

TASK [Gathering Facts] ***************************************************************************************************************************************
12:51:45 I mitogen.ctx.ssh.common.example.com.sudo.root: stdout: exc: 'DistributionFiles' object has no attribute 'parse_distribution_file_Archlinux'

ansible-playbook -i common.example.com, common.yml   8.59s user 2.84s system 13% cpu 1:22.70 total

_It stuck at gathering facts for few seconds and then shows message and after that work fine, can you please work on this to improve a bit_


**Without mitogen**

ansible-playbook -i common.example.com, common.yml   28.44s user 7.70s system 10% cpu 5:48.91 total

**Comment by dw** [comment]
Thanks for trying it out, and these results already look good! Can you tell me please, 

* how much latency exists between the host machine and the target? (Just ping it to find out)
* what is the OS of the target machine
* what version of Ansible are you using (I want to fix that ugly exception text!)
* how many steps were executed/skipped/etc? (Final line of output from Ansible)

Most likely the reason for stalling during gather_facts is because the link is quite high latency, and that is a bug with the current importer, however it could also be some other issue.

**Comment by dw** [comment]
Please also re-install the extension, I fixed a nasty bug where it leaves temporary directories everywhere in /tmp on the target machine :/

**Comment by arbabnazar** [comment]
- how much latency exists between the host machine and the target? (Just ping it to find out)
```sh
PING common.example.com (52.10.90.15): 56 data bytes
64 bytes from 52.20.90.15: icmp_seq=0 ttl=41 time=362.409 ms
64 bytes from 52.10.90.15: icmp_seq=1 ttl=41 time=384.681 ms
64 bytes from 52.10.90.15: icmp_seq=2 ttl=41 time=302.482 ms
64 bytes from 52.10.90.15: icmp_seq=3 ttl=41 time=322.624 ms
64 bytes from 52.10.90.15: icmp_seq=4 ttl=41 time=340.901 ms
64 bytes from 52.10.90.15: icmp_seq=5 ttl=41 time=259.983 ms
```

- what is the OS of the target machine

```sh Ubuntu 14.04.5 LTS```

- what version of Ansible are you using (I want to fix that ugly exception text!)

```sh 
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/arbab/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

- how many steps were executed/skipped/etc? (Final line of output from Ansible)

```sh
common.example.com         : ok=37   changed=1    unreachable=0    failed=0```

I have re-install the extension using:
```sh
pip install -U git+https://github.com/dw/mitogen.git
```
Is it OK or I need to uninstall and install again?

Thanks,

**Comment by dw** [comment]
Nope, the command you used is fine. pip install -U forces 'upgrade', which means de/reinstall

**Comment by arbabnazar** [comment]
@dw can you please explain bit about this message:
```sh
12:51:45 I mitogen.ctx.ssh.common.example.com.sudo.root: stdout: exc: 'DistributionFiles' object has no attribute 'parse_distribution_file_Archlinux'
```
Thanks

**Comment by dw** [comment]
It is a bug in the setup module that previously went unreported by Ansible, because the setup module continued to exit successfully, and stdout output was otherwise discarded by Ansible.

Mitogen logs stdout output by default, so there are probably many more cases of buggy modules logging junk to the stdout. Therefore I will need to handle this somehow, probably by hiding stdio output except when "ansible-playbook -v" is used, or similar

**Comment by arbabnazar** [comment]
@dw is `mitogen` is production ready? I have fleet of Ubuntu servers ~100 that we are managing through ansible. Can I use it in production. Please recommend. Thanks

**Comment by dw** [comment]
@arbabnazar I would be extremely careful about deploying it for the time being, without thoroughly testing every playbook you have in a staging environment beforehand, with the same variables as would be used in production. Ansible simply has too many moving parts to be sure I haven't missed anything. My big worries are around options like delegate_to, and some internals that are overridden that accept a username that does not appear to be needed any more.

The result is that it's possible that some commands may run as the wrong user or on the wrong host, which could be disastrous This code is less than a week old. It's worth remembering that just 3 hours ago, it was spamming temp directories all over the target machine!

Note that I am available for consulting work, and if this would be of significant benefit to you in production, feel free to drop me an e-mail on dw@botanicus.net to discuss. Otherwise, please just wait a few months, the 'experimental' label will eventually be dropped :)

**Comment by retr0h** [comment]
I'm wanting to install mitogen for ansible with pip as well.  When installing the pip package it is missing the `mitogen_ansible` directory.

Is this just not the way to go?  I was hoping to avoid having to download mitogen into a specific directory for ansible.
