### ISSUE TITLE
LoadSubmoduleTest and other mitogen.core.Importer tests deadlock

### ISSUE THREAD

**Issue by moreati** [dw/mitogen#97]
Running `importer_test.py` directly never completes. Any test involving `ImporterMixin` (and hence invoking `Importer`) never completes - it waits forever. The process does not respond to Ctrl-C, it must be killed.

This problem is being masked by #96

**Comment by dw** [comment]
I've hacked the tests back to life, but really we need some nice way to handle this case and many more like it - testing code that expects a remote participant.

Will need the same thing for writing tests for mitogen.service-consuming code.

I think this will always need a full Router and Broker setup, because e.g. in the case of the importer tests, because the process model changes (response was delivered from the thread running Importer), threading.Lock must be patched into an RLock by the tests. That's a whopping hack, and it should be very short lived
